# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='Network.RPC.Protopap.Proto',
  serialized_pb='\n\trpc.proto\x12\x1aNetwork.RPC.Protopap.Proto\"\x1c\n\nRPCRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\"\x92\x01\n\x0bRPCResponse\x12>\n\x06status\x18\x01 \x01(\x0e\x32..Network.RPC.Protopap.Proto.RPCResponse.Status\x12\x13\n\x0bstatus_info\x18\x02 \x01(\t\".\n\x06Status\x12\x06\n\x02OK\x10\x01\x12\r\n\tRPC_ERROR\x10\x02\x12\r\n\tAPP_ERROR\x10\x03\"!\n\tRPCPubSub\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t')



_RPCRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Network.RPC.Protopap.Proto.RPCResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RPC_ERROR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APP_ERROR', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=172,
  serialized_end=218,
)


_RPCREQUEST = _descriptor.Descriptor(
  name='RPCRequest',
  full_name='Network.RPC.Protopap.Proto.RPCRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='Network.RPC.Protopap.Proto.RPCRequest.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=69,
)


_RPCRESPONSE = _descriptor.Descriptor(
  name='RPCResponse',
  full_name='Network.RPC.Protopap.Proto.RPCResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Network.RPC.Protopap.Proto.RPCResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_info', full_name='Network.RPC.Protopap.Proto.RPCResponse.status_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RPCRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=72,
  serialized_end=218,
)


_RPCPUBSUB = _descriptor.Descriptor(
  name='RPCPubSub',
  full_name='Network.RPC.Protopap.Proto.RPCPubSub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='Network.RPC.Protopap.Proto.RPCPubSub.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=220,
  serialized_end=253,
)

_RPCRESPONSE.fields_by_name['status'].enum_type = _RPCRESPONSE_STATUS
_RPCRESPONSE_STATUS.containing_type = _RPCRESPONSE;
DESCRIPTOR.message_types_by_name['RPCRequest'] = _RPCREQUEST
DESCRIPTOR.message_types_by_name['RPCResponse'] = _RPCRESPONSE
DESCRIPTOR.message_types_by_name['RPCPubSub'] = _RPCPUBSUB

class RPCRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCREQUEST

  # @@protoc_insertion_point(class_scope:Network.RPC.Protopap.Proto.RPCRequest)

class RPCResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCRESPONSE

  # @@protoc_insertion_point(class_scope:Network.RPC.Protopap.Proto.RPCResponse)

class RPCPubSub(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCPUBSUB

  # @@protoc_insertion_point(class_scope:Network.RPC.Protopap.Proto.RPCPubSub)


# @@protoc_insertion_point(module_scope)
